### ISSUE TITLE
Backend setup using node.js and express

### ISSUE THREAD

**Issue by hamzathul** [MOHAMMED-IQRAMUL/FarmRuler#22]
I would like to set up a backend Express server to handle the endpoints, For login and signup

#Hacktoberfest

**Comment by MOHAMMED-IQRAMUL** [comment]
Go On,
Make a Good Little Documentation On what You Have done After You Are done With Logic in the folder ```Backend/README.md```
All The Best,
After Contributing Make shure to  Add your data in  ```Contributing/README.md```
