### ISSUE TITLE
Feature Request: Dedicated Signup Page for Website Users

### ISSUE THREAD

**Issue by Arpit529Srivastava** [MOHAMMED-IQRAMUL/FarmRuler#23]
**Is your feature request related to a problem? Please describe.**
Users currently lack a dedicated page to sign up for the website. Without this, new users are unable to create accounts, preventing them from accessing the full range of features the website offers. This limits engagement and user acquisition.

**Describe the solution you'd like**
A dedicated signup page should be created where users who have not registered on the website can easily create an account. This page should:
-Include input fields for essential details such as username, email, password, and confirmation password.
Validate input fields

**Describe alternatives you've considered**
Embedded signup form: Adding a signup form as a modal or part of another page (like the homepage), rather than a dedicated signup page.

**Additional context**
Adding a "Terms of Service" and "Privacy Policy" checkbox that users must agree to before signing up.

**Comment by Arpit529Srivastava** [comment]
@MOHAMMED-IQRAMUL assign the issue to me under the label ```hacktoberfest```

**Comment by MOHAMMED-IQRAMUL** [comment]
Go On,
Make a Good Little Documentation On what You Have done After You Are done With Logic in the folder Backend/README.md

All The Best,
After Contributing Make shure to Add your data in Contributing/README.md

**Comment by Arpit529Srivastava** [comment]
sure will make the pr soon
thanks for assigning
