### ISSUE TITLE
Include a Logout button

### ISSUE THREAD

**Issue by khushiiagrawal** [MOHAMMED-IQRAMUL/FarmRuler#27]
**Is your feature request related to a problem? Please describe.**
Every website should have a logout button for the users so that whenever they want to logout from the website they can. This will enhance your website and also make it user friendly.

**Describe the solution you'd like**
I would like to add a **Log out** button to the homepage for the better experience of the user.

**Describe alternatives you've considered**
User can close the page or remove it from the history.

**Additional context**
Hoover in the button for enhancement

**Comment by khushiiagrawal** [comment]
Can you label it under hacktoberfest

**Comment by MOHAMMED-IQRAMUL** [comment]
Hi @khushiiagrawal ,

Currently, our website does not include a signup or login functionality, so a logout button wouldn't be applicable at this moment. However, we understand the importance of having such a feature for websites that do require user authentication.

I would suggest you to make a logOut button Component so in future it can be used.
