### ISSUE TITLE
Integration of Dark/Light Mode 

### ISSUE THREAD

**Issue by kumartushar0605** [MOHAMMED-IQRAMUL/FarmRuler#35]
Integration Of Dark<->Light Mode Toggle Options

**Comment by kumartushar0605** [comment]
@MOHAMMED-IQRAMUL please assign me i will do my best

**Comment by MOHAMMED-IQRAMUL** [comment]
All the Best.
After Contributing make shure to Add your data in ```Contributing/Readme.md```
