### ISSUE TITLE
 Dark Mode Toggle Button Not Functioning

### ISSUE THREAD

**Issue by codingkush** [MOHAMMED-IQRAMUL/FarmRuler#38]
Description: The dark mode toggle button is not working correctly. When the button is clicked, the theme does not switch between dark and light mode as expected.

Steps to Reproduce:

- Open the application.
- Click the dark mode toggle button.
- Observe that the theme does not change.

Expected Behavior: The application should switch to dark mode when the button is clicked and revert to light mode when clicked again.

Actual Behavior: The theme remains unchanged, or the toggle does not work consistently.

Screenshots : 

before ----->
![Screenshot 2024-10-09 191102](https://github.com/user-attachments/assets/4c2974d8-57c4-4ac6-a50e-f9b74c135066)

after------->
![Screenshot 2024-10-09 191045](https://github.com/user-attachments/assets/e607bfe7-107f-4c5a-aad4-77e78a14cb2d)

**Comment by MOHAMMED-IQRAMUL** [comment]
Yes, Shure Work On This,
I see the problem that initial state of theme is not choosen right, I always chooses drak as default but not change the theme
All The Best,
Make Shure To add your details in ```Contributing/Readme.md After Contribution```

**Comment by codingkush** [comment]
thank you
