### ISSUE TITLE
signup and signin buttons at the bottom not working

### ISSUE THREAD

**Issue by ChauhanGauri** [MOHAMMED-IQRAMUL/FarmRuler#41]
The signup and signin buttons at the bottom of the main page are not working. They should redirect to the signup page. Kindly assign me the issue under hacktoberfest.
![FarmRuler - Google Chrome 10_17_2024 10_24_15 AM](https://github.com/user-attachments/assets/a7c601cf-5d61-4fcc-bdf0-ba16c00b3679)

**Comment by MOHAMMED-IQRAMUL** [comment]
Great idea ! Sure you can definitely work .
All The Best,
Make Shure To add your details in ```Contributing/Readme.md``` After Contribution

**Comment by JanumalaAkhilendra** [comment]
It this issue is open , I would like to work on it .:)

**Comment by MOHAMMED-IQRAMUL** [comment]
Great idea ! Sure you can definitely work .
All The Best,
Make Shure To add your details in ```Contributing/Readme.md``` After Contribution
