### ISSUE TITLE
Feature/sign-up button text not showing on hover

### ISSUE THREAD

**Issue by Aditya-PS-05** [MOHAMMED-IQRAMUL/FarmRuler#46]
![Screenshot from 2024-10-23 20-18-04](https://github.com/user-attachments/assets/d44c13ab-4fdf-4487-862a-b7652821278c)

Please assign it to me under `hacktoberfest` label.

**Comment by MOHAMMED-IQRAMUL** [comment]
Great Idea,
All the Best.
After Contributing Make shure to Add your details in ```Contributing/README.md```
