### ISSUE TITLE
Integrate Sigin and Signup functionalities of frontend and backend.

### ISSUE THREAD

**Issue by PradeepG-07** [MOHAMMED-IQRAMUL/FarmRuler#50]
Would like to integrate backend and frontend with help of axios.

I would like to work on this issue.

**Comment by MOHAMMED-IQRAMUL** [comment]
Thank you for expressing interest in working on the integration of our backend and frontend using Axios. We appreciate your willingness to contribute to our web app

 **Contribution Guidelines**
Please make sure to follow our contribution guidelines, which include:
-Writing clean, modular, and well-documented code.
-Following our code style and linting rules.
-Testing your code thoroughly before submitting a pull request.

**Next Steps**
Let us know if you have any questions or need further information to get started. We are excited to have you on board and look forward to your contributions.

Add you Details once done with contributing in ```Contrubuting/Readme.md```

**Comment by PradeepG-07** [comment]
I would like to do this with help of contexts and update the states in the navigation as well. I want to know where should i navigate the user after successfull login?

**Comment by MOHAMMED-IQRAMUL** [comment]
After Login the user gets redirected to ```/dashboard``` and also further features of dashboard login is essential

**Comment by PradeepG-07** [comment]
Hi @MOHAMMED-IQRAMUL I have linked the pull request regarding this issue. Please verify it.
