### ISSUE TITLE
Add toasts to enhance ui experience of user.

### ISSUE THREAD

**Issue by PradeepG-07** [MOHAMMED-IQRAMUL/FarmRuler#52]
- **Would to integrate react-hot-toast to display the webapp state such as validating credentials, signup successufull, invalid credentails etc.**
- Click [here](https://react-hot-toast.com/) to visit **react-hot-toast package.**
- I would like to work on this issue.

**Comment by MOHAMMED-IQRAMUL** [comment]
Thank you for expressing interest in working . We appreciate your willingness to contribute to our web app.
You can Proceed. All the best
Let us know if you have any questions or need further information to get started. We are excited to have you on board and look forward to your contributions.

**Comment by PradeepG-07** [comment]
Hi @MOHAMMED-IQRAMUL , I have made the necessary changes to add toasts. 
- Please comment the changes to be made if any.
