### ISSUE TITLE
Rename 'Sign In' To 'Log In'

### ISSUE THREAD

**Issue by Devanshukoli** [MOHAMMED-IQRAMUL/FarmRuler#58]
**Describe the bug**
In Navbar of the website, there is 2 buttons of auth, in which **Sign In** and **Sign Up**, They are very similar and in quick glance can be mistaken, So I propose that we should change *Sign In* into *Log In*.

**To Reproduce**
- It shows on the **Homepage** of the website.

**Screenshots**
- Here, you can see that in *Navbar*, there is *sign in* and *sign up* option..
![image](https://github.com/user-attachments/assets/ff023aa2-f611-4acb-b448-7adf27e5ccd1)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser: Edge
 - Version: latest

**Additional context**
- I would like to work on this issue. If you like I can work on it. 😃

**Comment by MOHAMMED-IQRAMUL** [comment]
Great Idea,
You can Work on this,
After Contributing add your details in ```Contributing/Readme.md```
